package org.redhat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-17T11:33:04.030+05:30
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://redhat.org", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://redhat.org")
    @WebResult(name = "outputSOATest", targetNamespace = "http://redhat.org", partName = "out")
    public OutputSOATest soaTest(

        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://redhat.org")
        InputSOATest in
    );
}
